# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82654fe667a2ec30b9cc2e53e636929daf91321169de83c619db246c7a6d407ad12dbb8a4e141fd56373d1d10c98c1e93fd350d6191b3d648130a4fcb8c9aed6

test:
  secret_key_base: b3eff83225eb5f401fa33fee126f35a7441876606606dbce993bc234da5fad0190028971d637a5505a84c0fe69de655dfac315560c87e7caa362e6017feb8fe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
